spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
    routes:
      - id: shopping_cart_circuitbreaker_route
        uri: lb://shopping-cart
        predicates:
          - Path=/shopping-cart/**
#        filters:
#          - CircuitBreaker=myCircuitBreaker
      - id: shopping_store_circuitbreaker_route
        uri: lb://shopping-store
        predicates:
          - Path=/shopping-store/**
        filters:
          - name: Retry
            args:
              retries: 3
              exceptions: ProductNotFoundException
              backoff:
                firstBackoff: 10ms
                maxBackoff: 50ms
                factor: 2
                basedOnPreviousValue: false
server:
  port: 8080

