spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}
  eureka:
    client:
      service-url:
        default-zone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
server:
  port: 0
