aggregator:
  kafka:
    topics:
      telemetry-sensors: telemetry.sensors.v1
      telemetry-snapshots: telemetry.snapshots.v1
    producer:
      bootstrap.servers: localhost:9092
      value.serializer: "ru.yandex.practicum.kafka.GeneralAvroSerializer"
      key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
    consumer:
      group.id: aggregator-consumer-group
      auto.offset.reset: earliest
      key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value.deserializer: "ru.yandex.practicum.kafka.SensorEventDeserializer"
      bootstrap.servers: localhost:9092