spring:
  application:
    name: shopping-store
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka/
resilience4j.circuitbreaker:
  instances:
    shopping-store:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000 # 10 секунд в миллисекундах
      permitted-number-of-calls-in-half-open-state: 3
      sliding-window-type: COUNT_BASED
      minimum-number-of-calls: 5
      automatic-transition-from-open-to-half-open-enabled: true